Search field to all results
Archinowsk/konsti-client pull request #7
Opened 2020-02-26 20:49 UTC by Altesmi

At the moment the results are just displayed in the results page. This branch adds a search field to the "all signup results" page which sorts the results based on either the username or game title. 

term "find" is added to locales

2020-03-02 18:04 UTC, Archinowsk reviewed
Huomasin, että `ResultsList.tsx` komponentin vastaanottaman `results` arrayn arvoilla on ylimääräinen muuttuja `_id`. Jatkohommana voisi olla sen siivoaminen pois. Se luultavasti palautetaan kannasta, mikä ei ole tarkoituksenmukaista. Kannattaa kattoa, siivoaako sen pois suoraan, kun luetaan tietoja kannasta vai vasta frontissa, kun kutsutaan rajapintaa. Molempi parempi.

![Capture](https://user-images.githubusercontent.com/1327412/75704169-894a1a80-5cc1-11ea-9e78-9cf9f0ccc6b7.PNG)

2020-03-02 18:04 UTC, Archinowsk commented on src/views/results/components/ResultsList.tsx
> +  const [searchResults, setSearchResults] = React.useState<any>(null);
`any` tyypin käyttämistä kannattaa välttää jos vaan mahdollista. Sitä ei ole kokonaan kielletty, koska sitä on vanhastaan käytössä, mutta tavoitteena on poistaa se kaikkialta.

Tässä tapauksessa `searchResults` etsii sopivia `results` objekteja eli on results-array. Results on määritelty täällä: https://github.com/Archinowsk/konsti-client/blob/master/src/typings/result.typings.ts. Se on tyypiltään:

```
export interface Result {
  username: string;
  enteredGame: Signup;
}
```

Tiedostossa `ResultsList.tsx` importataan jo Results-tyyppi: https://github.com/Archinowsk/konsti-client/blob/search_field_to_all_results/src/views/results/components/ResultsList.tsx#L5

Tuon `searchResults` tilamuuttujan voi siis tyypittää näin: 

```  
const [searchResults, setSearchResults] = React.useState<Result[]>([]);
```

2020-03-02 18:04 UTC, Archinowsk commented on src/views/results/components/ResultsList.tsx
> +  const [searchResults, setSearchResults] = React.useState<any>(null);
Huomasin, että `results`-muuttujilla on myös ylimääräinen muuttuja `_id`. Jatkohommana voisi olla sen siivoaminen pois. Se luultavasti palautetaan kannasta, mikä ei ole tarkoituksenmukaista. Kannattaa kattoa, siivoaako sen pois suoraan, kun luetaan tietoja kannasta vai vasta frontissa, kun kutsutaan rajapintaa.

2020-03-02 18:21 UTC, Archinowsk requested changes

2020-03-02 18:21 UTC, Archinowsk commented on src/views/results/components/ResultsList.tsx
> +        <br />
Ei kannata käyttää HTML-elementtejä sivun välyksien säätämiseen. CSS-tyylitiedostot sopii paremmin tähän tarkoitukseen. Jos tarvii väliä, niin määrittele jollekin ympärillä olevalle elementille `margin`ia.

Projekti käyttää tällä hetkellä CSS-tiedostoja, mitä yritetään pitää järjestyksessä nimeämiskäytännöillä. Esimerkiksi Results-näkymän tyylit on tiedostossa https://github.com/Archinowsk/konsti-client/blob/master/src/styles/results.css. CSS-tiedostoista viitataan HTML-elementteihin `className` parametrilla, esim näin: `<div className='results-list'>`.

Haluaisin vaihtaa irralliset CSS-tiedostot tyylitettyihin komponentteihin (`styled-components`), jolloin komponentti ja tyylit ovat samassa tiedostossa, mutta tätä ei ole vielä tehty.

2020-03-02 18:29 UTC, Archinowsk commented
Kun hakukentän valitsee niin sen ympärille ilmestyy reunus, että kenttä on valittu. 
![image](https://user-images.githubusercontent.com/1327412/75705624-666d3580-5cc4-11ea-8676-e21ed83e128e.png)

Tämä hiukan muuttaa kentän kokoa, mikä aiheuttaa pienen nykäisyn sivun ulkoasussa. Find-labelille ja kentälle voisi laittaa parent-elementin (esim <div></div>), jolle määrittää korkeutta siten, että rivin korkus ei muutu kenttää valitessa.

2020-03-15 17:01 UTC, Altesmi commented
Tein siun ehdottamat muutokset. 

Yksi kysymys jäi vielä: huomasin, että tulokset eivät latautuneet ollenkaan, kun All Signup Results -sivu ladattiin ensimmäisen kerran. Yritin korjata tätä viemällä SearchResults stateen defaulttina propseina tulleen results-olion. Tämä ei kuitenkaan toiminut oletettavasti siitä syystä, että kun searchResults muuttujaa alustetaan, results-olio on vielä tyhjä. Korjasin ongelman mielestäni vähän purkkamaisesti niin, että searchTermin ollessa välilyönti (' ') annetaan ResultsBy... komponenteille alkuperäinen results-taulukko muussa tapauksessa searchResults-taulukko. Keksitkö tähän parempaa tapaa?

2020-03-18 18:13 UTC, Archinowsk requested changes

2020-03-18 18:13 UTC, Archinowsk commented on src/views/results/components/ResultsList.tsx
> +  const [searchTerm, setSearchTerm] = React.useState<string>(' ');
Onko tässä tarkoituksella vai vahingossa välilyönti staten oletusarvossa? Jos vahingossa niin voisi yhtenäistää muiden kanssa `' '` -> `''`

2020-03-18 18:13 UTC, Archinowsk commented on src/views/results/components/ResultsList.tsx
> +const FindField = styled.div`
Varmaan aika makuasia, mutta olin aikaisemmin laittanut nuo komponenttien tyylit tiedoston loppuun, React-komponentin jälkeen. Voisi olla hyvä idea seurata samaa käytäntöä kaikkialla.

2020-03-18 18:13 UTC, Archinowsk commented on .eslintrc.js
> +    '@typescript-eslint/no-dupe-class-members': 'off',
Oliko näiden sääntöjen pois ottamisessa mikä ajatus?

2020-03-18 18:13 UTC, Archinowsk commented on src/views/results/components/ResultsList.tsx
> +      {console.log(searchTerm)}
Tää on varmaan jäänyt.

2020-03-18 18:13 UTC, Archinowsk commented on src/views/results/components/ResultsList.tsx
> +          results={searchTerm !== ' ' ? searchResults : results}
Tässä voi myös verrata `falsy` tarkastuksella: `!searchTerm`. Falsy kattaa `null`, `undefined`, `0` ja tyhjä string.

Eli: `results={!searchTerm ? searchResults : results}`

2020-03-18 18:13 UTC, Archinowsk commented on src/views/results/components/ResultsList.tsx
> +          results={searchTerm !== ' ' ? searchResults : results}
Tässä sama eli voisi tarkastaa `!searchTerm`. Yksi syy vaihtaa `' '` -> `''` on myös, että jos joku muuttaisi nyt oletusarvon `' '` -> `''` niin tämä tarkastus hajoaisi. Tämä ongelma ei poistu oletusarvolla `''`, mutta tuo on yleisempi :).

2020-03-18 18:31 UTC, Archinowsk commented on src/views/results/components/ResultsList.tsx
> +  const [searchResults, setSearchResults] = React.useState<Result[]>([]);
Sanoin tästä aikaisemmin väärin. Tyyppi ei ole `Result[]` vaan `readonly Result[]` :). Sen näkee Props-tyypeistä.

2020-03-18 18:34 UTC, Archinowsk commented
> Yksi kysymys jäi vielä: huomasin, että tulokset eivät latautuneet ollenkaan, kun All Signup Results -sivu ladattiin ensimmäisen kerran. Yritin korjata tätä viemällä SearchResults stateen defaulttina propseina tulleen results-olion. Tämä ei kuitenkaan toiminut oletettavasti siitä syystä, että kun searchResults muuttujaa alustetaan, results-olio on vielä tyhjä. Korjasin ongelman mielestäni vähän purkkamaisesti niin, että searchTermin ollessa välilyönti (' ') annetaan ResultsBy... komponenteille alkuperäinen results-taulukko muussa tapauksessa searchResults-taulukko. Keksitkö tähän parempaa tapaa?

Tää korjautuu ainakin sillä, että hakutermiä seuraavaan `useEffect` funktioon lisätään seurattavien muuttujien listalle myös `results`.

Eli näin:

```
  React.useEffect(() => {
    setSearchResults(
      results.filter(result => {
        return (
          result.username.toLowerCase().includes(searchTerm.toLowerCase()) ||
          result.enteredGame.gameDetails.title
            .toLowerCase()
            .includes(searchTerm.toLowerCase())
        );
      })
    );
  }, [searchTerm, results]);
```

2020-03-26 10:46 UTC, Altesmi commented
- Lisäsin aikaisemmin poistety TS-EsSint säännöt (virheilmoituksen poistui, kun päivitin oman vscoden uusimpaan versioon)

- Poistin console.login

- Siirsin styled komponentit react-komponentin jälkeen

- Lisäsin results-taulukon seurattavien muuttujien joukkoon useEffect-funktiossa. Kiitos neuvost!

2020-03-26 18:18 UTC, Archinowsk approved these changes
Näyttää hyvältä! Sisään vaan!

2020-03-27 08:37 UTC, merged